// const ADD_DOGS = "ADD_DOGS";
// const ADD_TEMPERAMENTS = " ADD_TEMPERAMENTS";
// const ADD_BREEDS = "ADD_BREEDS";
// const ORDER_ASC = "ORDER_ASC";
// const ORDER_DESC = "SORT_BY_WEIGHT_DESC";
// const SORT_ALPHABETICALLY_ASC = "SORT_ALPHABETICALLY_ASC";
// const SORT_ALPHABETICALLY_DESC = "SORT_ALPHABETICALLY_DESC";

// export {
//   ADD_DOGS,
//   ADD_TEMPERAMENTS,
//   ADD_BREEDS,
//   ORDER_ASC,
//   ORDER_DESC,
//   SORT_ALPHABETICALLY_ASC,
//   SORT_ALPHABETICALLY_DESC,
// };
